name: Publish on Github

on: [ pull_request, workflow_dispatch ]

env:
  MINECRAFT_VERSION: 1.20.4
  JAVA_VERSION: 21
  VERSION: 1.0.1

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 21

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod  +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Publish (Github)
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-tag: "v${{env.VERSION}}"
          github-token: "${{secrets.GH_TOKEN}}"

          name: "Arc SMP"
          version: "mc1.20.4-${{env.VERSION}}"
          version-type: release

          loaders: fabric
          game-versions: "${{env.MINECRAFT_VERSION}}"
          java: "${{env.JAVA_VERSION}}"